[project]
src = "src"
out = "out"
dot_env = ".env"
save_abi_path = "abis"
default_network_name = "mainnet-fork"
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "snekmate",
]

[networks.contracts]
weth = { abi = "abis/weth.json" }
usdc = { abi = "abis/usdc.json" }
uniswap_swap_router = { abi = "abis/uniswap_swap_router.json" }
aavev3_pool_address_provider = { abi = "abis/aave3_pool_address_provider.json" }
pool = { abi = "abis/pool.json" }
l2pool = { abi = "abis/l2pool.json" }
aave_protocol_data_provider = { abi = "abis/aave_protocol_data_provider.json" }
eth_usd_price_feed = { abi = "abis/eth_usd_price_feed.json" }
usdc_usd_price_feed = { abi = "abis/usdc_usd_price_feed.json" }
master_minter = { abi = "abis/master_minter.json" } 

[networks.mainnet-fork]
url = "$MAINNET_RPC_URL"
chain_id = 1
fork = true
is_zksync = false

[networks.arbitrum-fork]
url = "$ARBITRUM_RPC_URL"
chain_id = 42161
fork = true
is_zksync = false
explorer_uri = "https://api.arbiscan.io"
explorer_api_key = "$ARBISCAN_API_KEY"

[networks.mainnet-fork.contracts]
weth = { address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" }
usdc = { address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" }
uniswap_swap_router = { address = "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45" } #ini harusnya diubah ke universal router. pake contract lama. update uniswap
aavev3_pool_address_provider = { address = "0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e" }
aave_protocol_data_provider = { address = "0x41393e5e337606dc3821075Af65AeE84D7688CBD" }
eth_usd_price_feed = { address = "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419" }
usdc_usd_price_feed = { address = "0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6" }

[networks.arbitrum-fork.contracts]
weth = { address = "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"}
usdc = { address = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"}
uniswap_swap_router = { address = "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45"} #ini harusnya diubah ke universal router. pake contract lama. update uniswap
aavev3_pool_address_provider = {address = "0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb"}
aave_protocol_data_provider = { address = "0x14496b405D62c24F91f04Cda1c69Dc526D56fDE5" }
eth_usd_price_feed = { address = "0x639Fe6ab55C921f74e7fac1ee960C0B6293ba612"}
usdc_usd_price_feed = { address = "0x50834F3163758fcC1Df9973b6e91f0F0F0434aD3"}
l2_pool = { address = "0x794a61358D6845594F94dc1DB02A252b5b4814aD", abi = "abis/l2pool.json" }

