[project]
name = "aether-rebalance-sc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "moccasin>=0.4.0",
    "titanoboa>=0.2.7",
    "vyper>=0.4.2",
]
